# Generated by Django 5.2.16 on 2026-07-19 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                ('post_url', models.URLField(unique=True)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('caption', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
